#include "app_controller.h"
#include "button_driver.h"
#include "ui_controller.h"
#include "flash_storage_driver.h"
#include <stdio.h>
#include "uart_port.h"
#include "system_time.h"
#include "platform_init.h"
#include "signal_generator_service.h"
#include "measurement_service.h"
#include "lcd1602_driver.h"
#include "debug_logger.h"
#include "error_manager.h"
#include "config_service.h"

void AppController_Init(void) {
  FlashStorage_Status_t flash_status;

  Platform_InitSystem();

  /* Error Manager starts before Flash so boot-time faults can be retained in
     RAM even though UART is not available yet. */
  ErrorManager_Init();
  ConfigService_Init();

  SystemTime_Init();
  ButtonDriver_Init();
  UartPort_Init(9600);
  DebugLogger_SetReady(1U);

  DebugLogger_Log(DEBUG_LEVEL_INFO, "APP", "Boot");
  ErrorManager_Flush();

  flash_status = FlashStorage_GetLastStatus();
  DebugLogger_Log(DEBUG_LEVEL_INFO, "APP",
            "Config F=%luHz D=%u%% Fstep=%u Dstep=%u (%s)",
            (unsigned long)ConfigService_GetFrequency(),
            (unsigned int)ConfigService_GetDuty(),
            (unsigned int)ConfigService_GetFrequencyStep(),
            (unsigned int)ConfigService_GetDutyStep(),
            FlashStorage_StatusString(flash_status));

  MeasurementService_Init();
  SignalGeneratorService_Init(ConfigService_GetFrequency(), (uint8_t)ConfigService_GetDuty());

  (void)Lcd1602Driver_Init();
  UiController_Init();

  DebugLogger_Log(DEBUG_LEVEL_INFO, "APP", "Init done, errors=%lu",
            (unsigned long)ErrorManager_Get_Total_Count());
}

void AppController_RunOnce(void) {
  ButtonEvent_t event;
  static uint32_t last_uart_timeout_count = 0U;
  uint32_t uart_timeout_count;

  /* Scan GPIO first. Debouncing and edge detection are owned by button_driver.c. */
  ButtonDriver_Process();

  /* Consume all button events generated by this scan. */
  while ((event = ButtonDriver_GetEvent()) != BUTTON_EVENT_NONE) {
    DebugLogger_Log(DEBUG_LEVEL_TRACE, "BUTTON", "event=%u", (unsigned int)event);
    UiController_HandleEvent(event);
  }

  UiController_Update();

  /* UART cannot report its own failure reliably, but the fault is still kept
     in Error Manager for debugger inspection and for a later recovered UART. */
  uart_timeout_count = UartPort_GetTxTimeoutCount();
  if (uart_timeout_count != last_uart_timeout_count) {
    last_uart_timeout_count = uart_timeout_count;
    ErrorManager_Report(ERROR_SOURCE_UART,
                        ERROR_CODE_UART_TX_TIMEOUT,
                        ERROR_SEVERITY_ERROR);
  }
}
